### ISSUE TITLE
Median distance

### ISSUE THREAD

**Issue by asw91666** [cbsropenproject/6dof_face#10]
Hello,

I was wondering if you might be able to share how the median distance was measured? It would be greatly appreciated if you could provide the code used for calculating the median. Thank you very much for your assistance.

**Comment by cbsropenproject** [comment]
Hi，please uncomment https://github.com/cbsropenproject/6dof_face/blob/main/data/arkit_dataset.py#L320C58-L320C58.

**Comment by asw91666** [comment]
Thank you! @
