### ISSUE TITLE
How to make  biwi_test.csv ?

### ISSUE THREAD

**Issue by wynsmile** [cbsropenproject/6dof_face#12]
Thank you for your great work, I would like to ask how to convert GT pose from BIWI dataset to RGB image and make biwi_test.csv file based on ARKitFace dataset? Looking forward to your reply.

**Comment by cbsropenproject** [comment]
Hi, please refer to https://github.com/cbsropenproject/6dof_face/blob/main/data/biwi_preprocess.py. I am sorry for the late reply.

**Comment by wynsmile** [comment]
> Hi, please refer to https://github.com/cbsropenproject/6dof_face/blob/main/data/biwi_preprocess.py. I am sorry for the late reply.
Thank you very much for your reply, which successfully solved my problem.
