### ISSUE TITLE
how to generate bbox of given image

### ISSUE THREAD

**Issue by ZivKidd** [cbsropenproject/6dof_face#13]
great job!
I want to test the method on my custom image, and I noticed the demo.py is able to do this, but the bbox of face is given in the code, how do I generate bbox of my custom image?
I have tried to generate bbox by insightface bbox or insightface landmark, but the result are not good
thank you so much

**Comment by cbsropenproject** [comment]
Hi, you can use the existed face detection method, such as retinaface (https://github.com/serengil/retinaface), to detect the face bboxes. Then you can use these codes to update the bboxes in the below：

            x_min = bboxes[index][0]
            y_min = bboxes[index][1]
            x_max = bboxes[index][2]
            y_max = bboxes[index][3]
            x_center = (x_min + x_max) / 2
            y_center = (y_min + y_max) / 2
            w, h = x_max - x_min, y_max - y_min
            size = max(w, h)
            ss = np.array([0.75, 0.75, 0.75, 0.75])
            left = x_center - ss[0] * size
            right = x_center + ss[1] * size
            top = y_center - ss[2] * size
            bottom = y_center + ss[3] * size
            src_pts = np.float32([
                [left, top],
                [left, bottom],
                [right, top]
            ])
                dst_pts = np.float32([
            [0, 0],
            [0, opt.img_size - 1],
            [opt.img_size - 1, 0]
           ])
            tform = cv2.getAffineTransform(src_pts, dst_pts)
            tform_inv = cv2.getAffineTransform(dst_pts, src_pts)
            img_crop = cv2.warpAffine(img, tform, (opt.img_size,) * 2)

"img_crop" can be used to estimate the face pose. 

In addition,  the extraction method of bounding boxes of training images and testing images should be same. This will impact the results of face pose.

**Comment by ZivKidd** [comment]
thanks so much !
