### ISSUE TITLE
How to access ARKitFace dataset？

### ISSUE THREAD

**Issue by Dancingmader** [cbsropenproject/6dof_face#14]
Excuse me, I am trying to access the ARKitFace dataset, but I have not received any response after sending an email to cbsropenproject@outlook.com following the instructions in the readme file. Is there any other way that I can access this dataset or someone else that I should contact for help?

**Comment by cbsropenproject** [comment]
I am sorry for that. I checked the spam box and found an email. maybe it is yours. I have replied to it. You can check it. If there is some problem, you can contact us here.
