### ISSUE TITLE
How to Calculate Head Pose

### ISSUE THREAD

**Issue by zzbwanshui** [cbsropenproject/6dof_face#5]
How is the entire coordinate system of this article defined? This is very important for converting the rotation matrix into 3 Euler angles, or I want to know what your combined rotation looks like (xyz or other forms ), I want to reproduce how your head pose is obtained based on your thesis, but I found that after the rotation vector you obtained through cv2.solvePnPRansac and then converted into a rotation matrix through cv2.Rodrigues, I I want to convert the rotation matrix to Euler angles, but I don't know the coordinate system definition and combined rotation form on your side, and I can't get the final Euler angles (yaw, pitch, roll)

**Comment by cbsropenproject** [comment]
@zzbwanshui please refer to https://github.com/cbsropenproject/6dof_face/blob/main/models/perspnet_model.py#L227, and https://github.com/o0Helloworld0o-ustc/ECCV2022_WCPA_track2/blob/master/visualization.ipynb.
