### ISSUE TITLE
Data conversion of arkit？

### ISSUE THREAD

**Issue by zhiyoujingtian** [cbsropenproject/6dof_face#7]
It is convenient to describe, how to draw the face vertices obtained from arkit on the image? I follow the following connection for spatial conversion, drawing errors
https://developer.apple.com/forums/thread/717534

 I transform the face vertices to world coordinates using faceAnchor.transform, then to camera coordinates using scceneView.session.currentFrame?.camera.transform, and then to image coordinates using currentFrame?.camera.intrinsics.

**Comment by cbsropenproject** [comment]
please refer to https://github.com/o0Helloworld0o-ustc/ECCV2022_WCPA_track2/blob/master/visualization.ipynb.

**Comment by zhiyoujingtian** [comment]
> please refer to https://github.com/o0Helloworld0o-ustc/ECCV2022_WCPA_track2/blob/master/visualization.ipynb.

Thank you for your reply. I carefully read the recommended visualization link code.
The key is projection_matrix. How do you get projection_matrix from arkit?
Is it the projectionMatrix attribute data of ARcamera? It is described in the api as follows: A transform matrix appropriate for rendering 3D content to match the image captured by the camera.

**Comment by cbsropenproject** [comment]
You need to read and try the information of ARkit in apple api. All of our matrixes are from the apple. Our original information are missed.
