### ISSUE TITLE
Evaluation on BIWI

### ISSUE THREAD

**Issue by asw91666** [cbsropenproject/6dof_face#9]
Hi.
I evaluated your model on the BIWI using the code you provided.

Used GT mesh (from obj file)
Used pred bbox (from FAN that you referenced in your paper)
Used your code for the rotation, translation, and ADD evaluation.
The results are as follows:

"mae_r": "4.35 degree",
"pitch_mae": "5.20 degree",
"roll_mae": "3.59 degree",
"yaw_mae": "4.27 degree"

"mae_t": "26.23 mm",
"tx_mae": "14.56 mm",
"ty_mae": "18.18 mm",
"tz_mae": "45.94 mm",

"ADD": "57.50 mm",

The rotation error and translation error are slightly worse than the performance reported in the paper, but I believe this could be attributed to the details during the implementation. However, the ADD I measured is significantly better than what was reported in the paper. Do you have any idea why this might be the case?

**Comment by cbsropenproject** [comment]
For ADD result, we found a bug in our code, we used a random model which should be the GT model. We forgot to change it. For other metrics, the results should be similar to ours. Please check the RGB images and transformed GT pose according to ARKitFace dataset.

**Comment by asw91666** [comment]
Ok Thanks !

**Comment by cbsropenproject** [comment]
We have updated our trained model. Please download the newest model from the link in readme.
